### ISSUE TITLE
TypeError: ConsolAS is not a constructor

### ISSUE THREAD

**Issue by brew-guy** [WildH0g/consolas#1]
I can't get the example to work with the copy-paste minified script from dist in Google Apps Script. It works if I change first line to `var d = (function (d) {` and create the `cx` instance with `const cx = new d.ConsolAS();`. What am I doing wrong?

**Comment by WildH0g** [comment]
Good catch, thanks for the issue! It's fixed.

**Comment by WildH0g** [comment]
Fixed  `build:cp` step with the Vite plugin.
