### ISSUE TITLE
Implementing array of objects

### ISSUE THREAD

**Issue by brew-guy** [WildH0g/consolas#2]
How about adding recognition of tables provided in the format of array of objects:

data = [
    { id: 1,
    first_name: 'Johan',
    last_name: 'McMenamy',
    email: 'jmcmenamy0@techcrunch.com',
    gender: 'Male',
    ip_address: '41.114.226.125' },
  { id: 2,
    first_name: 'Kevyn',
    last_name: 'Pedder',
    email: 'kpedder1@godaddy.com',
    gender: 'Female',
    ip_address: '66.97.60.249' }
]

**Comment by WildH0g** [comment]
Sounds like a good idea. This implies a few other things:

- format the array in a readable way
- use camel case
- add it to the unit tests (and make sure they pass)
- add it to the README

**Comment by WildH0g** [comment]
Arrays of objects were not actually functional in the library. They are now.
